language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=7.2
    - BASE_IMAGE_STABILITY_TAG=4.1.0
  matrix:
    - TAG=7.2 PHP_VER=7.2 EXTRA_TAG=7
    - TAG=7.1 PHP_VER=7.1
    - TAG=7.0 PHP_VER=7.0
    - TAG=5.6 PHP_VER=5.6 EXTRA_TAG=5
    - TAG=7.2-dev PHP_VER=7.2 PHP_DEV=1 EXTRA_TAG=7-dev
    - TAG=7.1-dev PHP_VER=7.1 PHP_DEV=1
    - TAG=7.0-dev PHP_VER=7.0 PHP_DEV=1
    - TAG=5.6-dev PHP_VER=5.6 PHP_DEV=1 EXTRA_TAG=5-dev

script:
  - make && make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis_release"
