language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.4.6
  matrix:
    - PHP_VER=7.2 TAGS=7.2,7,latest
    - PHP_VER=7.1 TAGS=7.1
    - PHP_VER=7.0 TAGS=7.0
    - PHP_VER=5.6 TAGS=5.6
    - PHP_VER=7.2 PHP_DEV=1 TAGS=7.2-dev,7-dev
    - PHP_VER=7.1 PHP_DEV=1 TAGS=7.1-dev
    - PHP_VER=7.0 PHP_DEV=1 TAGS=7.0-dev
    - PHP_VER=5.6 PHP_DEV=1 TAGS=5.6-dev,5-dev
    - PHP_VER=7.2 PHP_DEV_MACOS=1 TAGS=7.2-dev-macos,7-dev-macos
    - PHP_VER=7.1 PHP_DEV_MACOS=1 TAGS=7.1-dev-macos
    - PHP_VER=7.0 PHP_DEV_MACOS=1 TAGS=7.0-dev-macos
    - PHP_VER=5.6 PHP_DEV_MACOS=1 TAGS=5.6-dev-macos,5-dev-macos

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
