language: bash

services:
- docker

env:
  global:
  - BASE_IMAGE_STABILITY_TAG=4.14.6
  matrix:
  - PHP_VER=7.4 TAGS=7.4,7,latest
  - PHP_VER=7.3 TAGS=7.3
  - PHP_VER=7.2 TAGS=7.2
  - PHP_VER=7.4 PHP_DEV=1 TAGS=7.4-dev,7-dev,dev
  - PHP_VER=7.3 PHP_DEV=1 TAGS=7.3-dev
  - PHP_VER=7.2 PHP_DEV=1 TAGS=7.2-dev
  - PHP_VER=7.4 PHP_DEV_MACOS=1 TAGS=7.4-dev-macos,7-dev-macos,dev-macos
  - PHP_VER=7.3 PHP_DEV_MACOS=1 TAGS=7.3-dev-macos
  - PHP_VER=7.2 PHP_DEV_MACOS=1 TAGS=7.2-dev-macos

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
