#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
  set -x
fi

disclaimer="// Generated by Wodby (add before wp-settings.php include)."
wp_config="${WP_ROOT}/wp-config.php"

if [[ ! -f "${wp_config}" ]]; then
    cp -f "${WODBY_DIR_CONF}/wp-config.php" "${wp_config}"
elif [[ $( grep -ic "wodby.wp-config.php.tpl" "${wp_config}" ) -eq 0 ]]; then
    chmod 644 "${wp_config}"
    sed -i "/wp-settings.php/i \\
${disclaimer} \\
require_once '${WODBY_DIR_CONF}/wodby.wp-config.php';" "${wp_config}"
fi

wp --path="${WP_ROOT}" option update home "${BASE_URL}"
wp --path="${WP_ROOT}" option update siteurl "${BASE_URL}"

rm -rf "${WP_ROOT}/wp-content/uploads"
ln -sf "${WODBY_DIR_FILES}/public" "${WP_ROOT}/wp-content/uploads"
