#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

disclaimer="// Generated by Wodby (add before wp-settings.php include)."
wp_config="${WP_ROOT}/wp-config.php"

if [[ ! -f "${wp_config}" ]]; then
    cp -f "${WODBY_DIR_CONF}/wp-config.php" "${wp_config}"
elif [[ $( grep -ic "wodby.wp-config.php.tpl" "${wp_config}" ) -eq 0 ]]; then
    chmod 644 "${wp_config}"
    sed -i "/wp-settings.php/i \\
${disclaimer} \\
require_once '${WODBY_DIR_CONF}/wodby.wp-config.php';" "${wp_config}"
fi

# Sync and symlink files dir if it's not symlink already.
WP_FILES="${WP_ROOT}/wp-content/uploads"
mkdir -p "${WP_FILES}"

if [[ ! -L "${WP_FILES}" ]]; then
    mkdir -p "${WODBY_DIR_FILES}/private"
    mkdir -p "${WODBY_DIR_FILES}/public"

    rsync -rlt --force "${WP_FILES}" "${WODBY_DIR_FILES}/public/"

    rm -rf "${WP_FILES}"
    ln -sf "${WODBY_DIR_FILES}/public" "${WP_FILES}"
fi
