<?php
/**
 * WordPress configuration file generated by Wodby.
 */

/**
 * Absolute path to the WordPress directory.
 */
if (!defined('ABSPATH')) {
  define('ABSPATH', __DIR__ . '/');
}

/**
 * Sets up wodby-specific configuration.
 */
require_once '{{ getenv "WODBY_DIR_CONF" }}/wodby.wp-config.php';

/**
 * Sets up WordPress vars and included files.
 */
require_once ABSPATH . 'wp-settings.php';