#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

disclaimer="// Generated by Wodby (add before wp-settings.php include)."
wp_config="${WP_ROOT}/wp-config.php"

mkdir -p "${WP_ROOT}"

if [[ ! -f "${wp_config}" ]]; then
    cp -f "${CONF_DIR}/wp-config.php" "${wp_config}"
elif [[ $( grep -ic "wodby.wp-config.php" "${wp_config}" ) -eq 0 ]]; then
    chmod 644 "${wp_config}"
    sed -i "/wp-settings.php/i \\
${disclaimer} \\
require_once '${CONF_DIR}/wodby.wp-config.php';" "${wp_config}"
fi

# Symlink files dir
wp_content="${WP_ROOT}/wp-content"
mkdir -p "${wp_content}"
init-public-storage.sh "${wp_content}/uploads"
